observations/urls.py
from django.urls import path

from observations import views

app_name = "observations"
urlpatterns = [
    path("videos/", views.VideoList.as_view(), name="video_list"),
    path("videos/<int:pk>/", views.VideoDetail.as_view(), name="video_detail"),
    path("videos/<int:pk>/create-observation/", views.PenguinObservationCreate.as_view(), name="penguinobservation_create"),
    path("videos/<int:pk>/observations/", views.VideoObservations.as_view(), name="video_observations"),
    path("videos/<int:pk>/complete/", views.VideoComplete.as_view(), name="video_complete"),
    path("help/", views.HelpPage.as_view(), name="help_page"),
    path("", views.SiteHome.as_view(), name="site_home"),
]

penguins/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path
from django.views.generic import RedirectView

admin.site.site_header = "Little Penguins Observations administration"
admin.site.index_title = "Little Penguins Observations"
admin.site.site_title = "Little Penguins Observations"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(template_name="logged_out.html"), name="logout"),
    path(
        "favicon.ico",
        RedirectView.as_view(url=f"{settings.STATIC_URL}favicon.ico"),
        name="favicon",
    ),
    path(
        "",
        include("observations.urls"),
    ),
]

observations/models.py
from datetime import date, datetime, timedelta

from django.conf import settings
from django.contrib.gis.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.forms import ValidationError
from django.urls import reverse
from django.utils import timezone


class Camera(models.Model):
    """A camera represents a single recording device at one of the sites that
    penguin observations are to be recorded.
    """

    name = models.CharField(max_length=100)
    camera_key = models.CharField(
        max_length=100,
        default="",
        help_text="Space-separated list of keys to match video recordings",
    )
    location = models.PointField(srid=4326, blank=True, null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        if self.active:
            return self.name
        else:
            return f"{self.name} (inactive)"

    def get_newest_video(self):
        video = Video.objects.filter(camera=self).first()  # Assumes ordering on Video.
        return video or None


class Video(models.Model):
    """A video represents a single recording from a camera on Penguin Island, against which
    penguins will be counted. Normally videos are one hour duration.
    """

    date = models.DateField(help_text="The date of the recording.")
    camera = models.ForeignKey(Camera, on_delete=models.PROTECT)
    uploaded_file = models.FileField(upload_to="videos")
    start_time = models.TimeField(help_text="The start time of the recording.")
    end_time = models.TimeField(help_text="The end time of the recording (usually 1h after start).")
    views = models.PositiveSmallIntegerField(default=0)
    mark_complete = models.BooleanField(default=False, help_text="Has this been viewed in its entirety by a reviewer?")
    completed_by = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name="videos_seen",
        verbose_name="Users who have seen this video",
    )

    class Meta:
        ordering = ["-date", "-start_time"]

    def __str__(self):
        return f"{self.camera.name}: {self.date} {self.start_time} - {self.end_time}"

    def get_absolute_url(self):
        return reverse("observations:video_detail", kwargs={"pk": self.pk})

    def get_video_filename(self):
        return self.uploaded_file.name.split("/")[-1]

    def get_content_disposition(self):
        filename = self.get_video_filename()
        return f"attachment; filename={filename}"

    def clean_date(self):
        if self.date > date.today():
            raise ValidationError("The 'Date' cannot be in the future!")

    def clean_end_time(self):
        if self.end_time < self.start_time:
            raise ValidationError("The 'End Time' cannot be before the 'Start Time'!")

    @property
    def duration(self):
        end = timedelta(
            hours=self.end_time.hour,
            minutes=self.end_time.minute,
            seconds=self.end_time.second,
        )
        start = timedelta(
            hours=self.start_time.hour,
            minutes=self.start_time.minute,
            seconds=self.start_time.second,
        )
        return end - start

    def get_start_datetime(self):
        return datetime.combine(self.date, self.start_time)


class PenguinObservation(models.Model):
    """Represents the observation of 0+ penguins at a particular frame within a video.
    More than one observation of the same penguins on the same video may exist, if >1 person
    watches the video and records an observation.
    """

    video = models.ForeignKey(Video, on_delete=models.PROTECT)
    observer = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="observations", on_delete=models.PROTECT)
    position = models.FloatField(
        default=0,
        null=True,
        verbose_name="Position (s)",
        help_text="Position in video (seconds from start)",
    )
    count = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        help_text="The count of penguins counted in this observation.",
    )
    comments = models.TextField(blank=True, null=True)
    raining = models.BooleanField(default=False, help_text="Was it raining at the time of the observation?")
    validated = models.BooleanField(default=True, verbose_name="Confirmed")

    def __str__(self):
        return "{} penguin(s) counted on {} at {} by {}".format(
            self.count,
            self.video.camera.name,
            self.get_observation_datetime(),
            self.observer,
        )

    def get_observation_datetime(self):
        """From the associated video and the value of `position`, derive the datetime of the penguin observation."""
        start = datetime.combine(self.video.date, self.video.start_time).astimezone(timezone.get_current_timezone())
        return start + timedelta(seconds=self.position)

observations/views.py
import json

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden, JsonResponse
from django.urls import reverse
from django.views.generic import DetailView, ListView, TemplateView, View
from django.views.generic.detail import SingleObjectMixin

from penguins.utils import breadcrumbs_html, get_next_pages, get_previous_pages, user_can_add_observations

from .models import Camera, PenguinObservation, Video


class SiteHome(LoginRequiredMixin, TemplateView):
    """Static template view for the site homepage."""

    template_name = "observations/site_home.html"
    http_method_names = ["get", "head", "options"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_superuser:
            context["superuser"] = True
        context["page_title"] = "Penguins | Home"
        context["page_heading"] = "Penguin Island cameras"
        context["geoserver_url"] = settings.GEOSERVER_URL
        context["layer_name"] = settings.LAYER_NAME
        queryset = Camera.objects.filter(active=True)
        context["active_cameras"] = queryset
        # Pass a list of cameras to the template context
        cameras_list = [
            {
                "pk": camera.pk,
                "name": camera.name,
                "x": camera.location.x,
                "y": camera.location.y,
            }
            for camera in queryset
        ]
        context["cameras_json"] = json.dumps(cameras_list)
        links = [(None, "Home")]
        context["breadcrumb_trail"] = breadcrumbs_html(links)
        return context


class HelpPage(LoginRequiredMixin, TemplateView):
    """Help page (static template view)."""

    template_name = "observations/help_page.html"
    http_method_names = ["get", "head", "options"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "Penguins | Help page"
        links = [(reverse("observations:site_home"), "Home"), (None, "Help")]
        context["breadcrumb_trail"] = breadcrumbs_html(links)
        if settings.EXAMPLE_VIDEO_URL:
            context["example_video_url"] = settings.EXAMPLE_VIDEO_URL
        else:
            context["example_video_url"] = None
        return context


class VideoList(LoginRequiredMixin, ListView):
    """User-facing list view for all videos."""

    template_name = "observations/video_list.html"
    model = Video
    paginate_by = 50
    http_method_names = ["get", "head", "options"]

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.GET.get("camera_id"):
            queryset = queryset.filter(camera__pk=self.request.GET["camera_id"])
        if self.request.GET.get("date"):
            # Django is nice enough to parse the date string for us.
            queryset = queryset.filter(date=self.request.GET["date"])
        if self.request.GET.get("completed"):
            completed = self.request.GET["completed"] == "true"
            queryset = queryset.filter(mark_complete=completed)
        if self.request.GET.get("views"):
            if self.request.GET["views"] == "false":
                queryset = queryset.filter(views=0)
            elif self.request.GET["views"] == "true":
                queryset = queryset.filter(views__gt=0)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_superuser:
            context["superuser"] = True
        context["can_add_observations"] = user_can_add_observations(self.request.user)
        context["page_title"] = "Penguins | Videos"
        context["page_heading"] = "Penguin Island videos"
        context["object_count"] = len(self.get_queryset())
        context["previous_pages"] = get_previous_pages(context["page_obj"])
        context["next_pages"] = get_next_pages(context["page_obj"])
        context["active_cameras"] = Camera.objects.filter(active=True)
        links = [(reverse("observations:site_home"), "Home"), (None, "Videos")]
        context["breadcrumb_trail"] = breadcrumbs_html(links)
        # Context for filter form.
        if self.request.GET.get("camera_id"):
            context["filter_camera_id"] = int(self.request.GET["camera_id"])
        if self.request.GET.get("date"):
            context["filter_date"] = self.request.GET["date"]
        if self.request.GET.get("completed"):
            context["filter_completed"] = self.request.GET["completed"]
        if self.request.GET.get("views"):
            context["filter_views"] = self.request.GET["views"]
        return context


class VideoDetail(LoginRequiredMixin, DetailView):
    """User-facing detail view for a single video, used to record new observations."""

    template_name = "observations/video_detail.html"
    model = Video
    http_method_names = ["get", "head", "options"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_superuser:
            context["superuser"] = True
        context["can_add_observations"] = user_can_add_observations(self.request.user)
        obj = self.get_object()
        context["page_title"] = f"Penguins | {obj}"
        links = [
            (reverse("observations:site_home"), "Home"),
            (reverse("observations:video_list"), "Videos"),
            (None, obj.pk),
        ]
        context["breadcrumb_trail"] = breadcrumbs_html(links)
        return context


class VideoObservations(LoginRequiredMixin, ListView):
    """Basic view to return the penguin observation objects for a given video, for the request user."""

    template_name = "observations/video_observations_table.html"
    model = PenguinObservation
    http_method_names = ["get", "head", "options"]

    def get_queryset(self):
        qs = super().get_queryset()
        video = Video.objects.get(pk=self.kwargs["pk"])
        qs = qs.filter(video=video, observer=self.request.user).order_by("position")
        return qs


class PenguinObservationCreate(LoginRequiredMixin, SingleObjectMixin, View):
    """API endpoint to create a new PenguinObservation on a parent Video."""

    model = Video
    http_method_names = ["post", "head", "options"]

    def dispatch(self, request, *args, **kwargs):
        if not user_can_add_observations(request.user):
            return HttpResponseForbidden("Unauthorised")
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        video = self.get_object()
        observation = PenguinObservation.objects.create(
            video=video,
            observer=request.user,
            position=int(request.POST["videoPosition"]),
            count=request.POST["penguinCount"],
            comments=request.POST["comments"],
        )
        d = {
            "id": observation.pk,
            "video_id": observation.video.pk,
            "observer": observation.observer.get_full_name(),
            "position": observation.position,
            "count": observation.count,
            "comments": observation.comments,
            "timestamp": observation.get_observation_datetime().isoformat(),
        }
        return JsonResponse(d)


class VideoComplete(LoginRequiredMixin, SingleObjectMixin, View):
    """API endpoint to mark a Video as 'complete'."""

    model = Video
    http_method_names = ["patch", "head", "options"]

    def dispatch(self, request, *args, **kwargs):
        if not user_can_add_observations(request.user):
            return HttpResponseForbidden("Unauthorised")
        return super().dispatch(request, *args, **kwargs)

    def patch(self, request, *args, **kwargs):
        video = self.get_object()
        video.mark_complete = True
        video.views = video.views + 1
        video.completed_by.add(request.user)
        video.save()
        d = {
            "id": video.pk,
            "date": video.date,
            "camera": str(video.camera),
            "file": video.file.url,
            "start_time": video.start_time,
            "end_time": video.end_time,
            "views": video.views,
            "mark_complete": video.mark_complete,
        }
        return JsonResponse(d)

observations/templates/observations/site_home.html
{% extends "base_penguins.html" %}
{% load static %}
{% block extra_style %}
    {{ block.super }}
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.css"
          integrity="sha512-h9FcoyWjHcOcmEVkxOfTLnmZFWIH0iZhZT1H2TbOq55xssQGEJHEaIm+PgoUaZbRvQTNTluNOEfb1ZRy6D3BOw=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
    <style>#map { width:100%; height: 480px;}</style>
{% endblock %}
{% block page_content_inner %}
    <div class="row my-1">
        <div class="col-md">
            <h1>Penguin Island site map</h1>
            <div class="card card-body" id="map"></div>
        </div>
        <div class="col-md">
            <h1>Active cameras</h1>
            <table class="table table-bordered table-hover">
                <tbody>
                    {% for camera in active_cameras %}
                        <tr>
                            <td>
                                <a href="{% url 'observations:video_list' %}?camera_id={{ camera.pk }}">{{ camera }} - {{ camera.video_set.count }} videos, latest {{ camera.get_newest_video.get_start_datetime }}</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}
{% block extra_js %}
    {{ block.super }}
    <script>
      const geoserverUrl = "{{ geoserver_url }}";
      const layerName = "{{ layer_name }}";
      const penguinIconUrl = "{% static 'img/penguin_icon.png' %}";
      const camerasJson = JSON.parse("{{ cameras_json|escapejs }}");
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.js"
            integrity="sha512-puJW3E/qXDqYp9IfhAI54BJEaWIfloJ7JWs7OeD5i6ruC9JZL1gERT1wjtwXFlh7CjE7ZJ+/vcRZRkIYIb6p4g=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"></script>
    <script src="{% static 'js/site_map.js' %}"></script>
    {# Iterate through the list of camera and add a marker to the map for each. #}
    <script>
      {% for camera in active_cameras %}
      var marker = L.marker([{{ camera.location.y}}, {{camera.location.x}}], { icon: penguinIcon }).addTo(map);
      var popupHtml = "<a href='{% url "observations:video_list" %}?camera_id={{ camera.pk }}'>{{ camera.name }}</a><br>{{ camera.video_set.count }} videos";
      marker.bindPopup(popupHtml);
      {% endfor %}
    </script>
{% endblock extra_js %}

observations/templates/observations/video_detail.html
{% extends "base_penguins.html" %}
{% load static %}
{% block extra_style %}
    {{ block.super }}
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/video.js/8.17.3/video-js.min.css"
          integrity="sha512-xQ+IvAl0/u0XWFWC0uoJLfQLKE+J3KZ/kPWpD/8ZoTw/pafvsQW0hudKW4lgZwk02eymBBpdwC0QfqrHUOhOhw=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/toastify-js/1.12.0/toastify.min.css"
          integrity="sha512-k+xZuzf4IaGQK9sSDjaNyrfwgxBfoF++7u6Q0ZVUs2rDczx9doNZkYXyyQbnJQcMR4o+IjvAcIj69hHxiOZEig=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
    <style type="text/css">
  /*
  I can't believe that we need to hack the CSS selector to display an element.
  Ref: https://github.com/videojs/video.js/issues/5751
  */
  .video-js .vjs-current-time { display: block; }
    </style>
{% endblock %}
{% block page_content_inner %}
    <div class="row">
        <div class="col">
            <div>
                <h1 id="pageHeading">
                    {{ object.camera }}: {{ object.date }} {{ object.start_time }} - {{ object.end_time }}
                    {% if object.mark_complete %}(completed){% endif %}
                </h1>
            </div>
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>Please note:</strong> the "Mark finished" button will not be enabled until you have finished watching the video until the end.
                <button type="button"
                        class="btn-close"
                        data-bs-dismiss="alert"
                        aria-label="Close"></button>
            </div>
            <div>
                <button type="button"
                        class="btn btn-primary"
                        id="addObservationButton"
                        data-bs-toggle="modal"
                        data-bs-target="#addObservationModal">Add an observation</button>
                <button type="button"
                        class="btn btn-success"
                        id="markFinishedButton"
                        data-action="{% url 'observations:video_complete' pk=object.pk %}"
                        disabled>Mark finished</button>
                {% if user.is_superuser %}
                    <a class="btn btn-secondary"
                       href="{{ object.uploaded_file.url }}?rscd={{ object.get_content_disposition }}"
                       role="button"
                       id="downloadButton">Download video</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="row my-1">
        <div class="col">
            <div class="embed-responsive embed-responsive-16by9">
                <video id="videoPlayer"
                       class="video-js vjs-fluid vjs-show-big-play-button-on-pause">
                    <source src="{{ object.uploaded_file.url }}" type="video/mp4" />
                    <p class="vjs-no-js">
                        To view this video please enable JavaScript, and consider upgrading to a web browser that
                        <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
                    </p>
                </video>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div>
                Your observations for this video:
                <br>
                <em>Note that video timestamp skipping may not work until the video is fully downloaded in your browser tab.</em>
            </div>
            <div id="videoObservationsTable"
                 hx-get="{% url 'observations:video_observations' pk=object.pk %}"
                 hx-trigger="load,observationCreated from:body"
                 hx-swap="innerHTML"></div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade"
         id="addObservationModal"
         tabindex="-1"
         aria-labelledby="addObservationModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="addObservationModalLabel">Add an observation</h1>
                    <button type="button"
                            class="btn-close"
                            data-bs-dismiss="modal"
                            aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="saveObservationForm"
                          onsubmit="event.preventDefault(); submitObservationForm(this);"
                          action="{% url 'observations:penguinobservation_create' pk=object.pk %}"
                          method="post">
                        {% csrf_token %}
                        <div class="row mb-3">
                            <label for="videoPosition" class="col-sm-2 col-form-label">Video position (seconds)</label>
                            <div class="col-sm-10">
                                <input type="text"
                                       readonly
                                       class="form-control-plaintext"
                                       id="videoPosition"
                                       name="videoPosition"
                                       value="0" />
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label for="penguinCount" class="col-sm-2 col-form-label">
                                <strong>No. of penguins<span class="asteriskField">*</span></strong>
                            </label>
                            <div class="col-sm-10">
                                <input type="number"
                                       min="0"
                                       class="form-control"
                                       id="penguinCount"
                                       name="penguinCount"
                                       required />
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label for="comments" class="col-sm-2 col-form-label">Comments</label>
                            <div class="col-sm-10">
                                <textarea class="form-control" id="comments" name="comments" rows="3"></textarea>
                            </div>
                        </div>
                        <div>
                            <button type="submit" class="btn btn-primary" id="saveObservationButton">Save observation</button>
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        </div>
                    </form>
                </div>
                <!-- /.modal-body -->
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
{% endblock page_content_inner %}
{% block base_js %}
    {{ block.super }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/htmx/2.0.0/htmx.min.js"
            integrity="sha512-Cpedvic0/Mgc3uRJ5apQ/ZYroPCZpatYEXGJayRaRNjKLaFualFxfxn97LJymznV+nC7y0/Hp/apHNwGpMimuw=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/video.js/8.17.3/video.min.js"
            integrity="sha512-gqDlEVSJBx2sY4FCoF8fElKc1JpQqbKnZSBmBEW/qQ6rRSyfIEAkevSH22LnGZ5vsNrhv79fM4S+AMmmCEMQKA=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-hotkeys/0.2.28/videojs.hotkeys.min.js"
            integrity="sha512-XFywGzDn2tPc+tF4RbOZdolw11XBdD3OgmAvnC+yoiD1qBSGVshZPZEq6d1XYzCrZpNrVXpPcuYPdx3k0QZkcw=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastify-js/1.12.0/toastify.min.js"
            integrity="sha512-0Yc4Jv5wX4+mjDuLxmHFGqgDtMFAEBLpPq/0nPVmAOwHPMkYXiS1YVYWTcrVQztftk/32089DDTyrCJO8hBCZw=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"></script>
    <script src="{% static 'js/video_player.js' %}"></script>
{% endblock %}

observations/templates/observations/video_list.html
{% extends "base_penguins.html" %}
{% block page_content_inner %}
    <div class="row">
        <div class="col">
            <h1>{{ page_heading }}</h1>
            <form class="row row-cols-lg-auto g-2 align-items-center"
                  action=""
                  method="get">
                <div class="col-12">
                    <div class="input-group">
                        <div class="input-group-text">Camera</div>
                        <select class="form-select"
                                aria-label="Select camera"
                                id="selectCamera"
                                name="camera_id"
                                onchange="this.form.submit()">
                            <option value="">--------</option>
                            {% for camera in active_cameras %}
                                <option value="{{ camera.pk }}"
                                        {% if camera.pk == filter_camera_id %}selected{% endif %}>
                                    {{ camera.name }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="col-12">
                    <div class="input-group">
                        <div class="input-group-text">Date</div>
                        <input type="date"
                               class="form-control"
                               aria-label="Select date"
                               {% if filter_date %}value="{{ filter_date }}"{% endif %}
                               id="selectDate"
                               name="date"
                               onchange="this.form.submit()" />
                    </div>
                </div>
                <div class="col-12">
                    <div class="input-group">
                        <div class="input-group-text">Completed?</div>
                        <select class="form-select"
                                aria-label="Select completed"
                                id="selectCompleted"
                                name="completed"
                                onchange="this.form.submit()">
                            <option value="">--------</option>
                            <option value="true"{% if filter_completed == "true" %} selected{% endif %}>Yes</option>
                            <option value="false"{% if filter_completed == "false" %} selected{% endif %}>No</option>
                        </select>
                    </div>
                </div>
                <div class="col-12">
                    <div class="input-group">
                        <div class="input-group-text">Has views?</div>
                        <select class="form-select"
                                aria-label="Have views"
                                id="selectCompleted"
                                name="views"
                                onchange="this.form.submit()">
                            <option value="">--------</option>
                            <option value="true"{% if filter_views == "true" %} selected{% endif %}>Yes</option>
                            <option value="false"{% if filter_views == "false" %} selected{% endif %}>No</option>
                        </select>
                    </div>
                </div>
            </form>
            {% if object_list %}
                <div class="mt-2">{% include "pagination.html" %}</div>
                <table class="table table-striped table-bordered table-condensed">
                    <thead>
                        <tr>
                            <th>Video</th>
                            <th>Views</th>
                            <th>Completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for obj in object_list %}
                            <tr>
                                <td>
                                    {% if can_add_observations %}
                                        <a href="{% url 'observations:video_detail' obj.pk %}">{{ obj.camera }}, {{ obj.date }} {{ obj.start_time }} - {{ obj.end_time }}</a>
                                    {% else %}
                                        {{ obj.camera }}, {{ obj.date }} {{ obj.start_time }} - {{ obj.end_time }}
                                    {% endif %}
                                </td>
                                <td>{{ obj.views }}</td>
                                <td>
                                    {% if obj.mark_complete %}
                                        <i class="fa-solid fa-check"></i>
                                    {% else %}
                                        <i class="fa-solid fa-xmark"></i>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% include "pagination.html" %}
            {% else %}
                <div class="my-4">No videos found.</div>
            {% endif %}
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
{% endblock page_content_inner %}