observations/urls.py
from django.urls import path

from observations import views

app_name = "observations"
urlpatterns = [
    path("videos/", views.VideoList.as_view(), name="video_list"),
    path("videos/<int:pk>/", views.VideoDetail.as_view(), name="video_detail"),
    path("videos/<int:pk>/create-observation/", views.PenguinObservationCreate.as_view(), name="penguinobservation_create"),
    path("videos/<int:pk>/observations/", views.VideoObservations.as_view(), name="video_observations"),
    path("videos/<int:pk>/complete/", views.VideoComplete.as_view(), name="video_complete"),
    path("help/", views.HelpPage.as_view(), name="help_page"),
    path("", views.SiteHome.as_view(), name="site_home"),
]

penguins/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path
from django.views.generic import RedirectView

admin.site.site_header = "Little Penguins Observations administration"
admin.site.index_title = "Little Penguins Observations"
admin.site.site_title = "Little Penguins Observations"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(template_name="logged_out.html"), name="logout"),
    path(
        "favicon.ico",
        RedirectView.as_view(url=f"{settings.STATIC_URL}favicon.ico"),
        name="favicon",
    ),
    path(
        "",
        include("observations.urls"),
    ),
]

penguins/templates/base_penguins.html
{% extends "webtemplate_dbca/base_b5.html" %}
{% load static %}
{% block extra_style %}
    {{ block.super }}
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/fontawesome.min.css"
          integrity="sha512-B46MVOJpI6RBsdcU307elYeStF2JKT87SsHZfRSkjVi4/iZ3912zXi45X5/CBr/GbCyLx6M1GQtTKYRd52Jxgw=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
          integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
    <style>
  .navbar-custom {
    background-color: #5393d2;
  }
  /* Change the brand and text color */
  .navbar-custom .navbar-brand, .navbar-custom .navbar-text {
    color: #ffffff;
  }
  /* Change the link color */
  .navbar-custom .navbar-nav .nav-link {
    color: #16283a;
  }
  /* Change the color of active or hovered links */
  .navbar-custom .nav-item.active .nav-link, .navbar-custom .nav-item:hover .nav-link {
    color: #ffffff;
  }
  .footer {
    background-color: #f5f5f5;
  }
    </style>
{% endblock %}
{% block navbar_brand %}
    <a class="navbar-brand d-block d-sm-none" href="/">{{ site_acronym }}</a>
    <a class="navbar-brand d-none d-sm-block" href="/">
        {% block navbar_logo %}
            <img class="d-inline-block"
                 src="{% static 'img/dbca_logo_sml.png' %}"
                 height="50">
        {% endblock navbar_logo %}
        <img class="d-inline-block"
             src="{% static 'img/penguin_logo.png' %}"
             height="50">
    </a>
{% endblock navbar_brand %}
{% block navbar_class %}navbar fixed-top navbar-expand-md navbar-custom{% endblock %}
{% block navbar_links %}
    {% if user.is_authenticated %}
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-item nav-link"
                       href="{% url 'observations:help_page' %}"
                       title="Protocol"><i class="fa-regular fa-circle-question"></i> Protocol</a>
                </li>
                {% if user.is_staff %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle"
                           href="#"
                           id="navbarDropdownMenuLink"
                           role="button"
                           data-bs-toggle="dropdown"
                           aria-expanded="false">
                            {% firstof user.get_full_name user.email %} <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end"
                            aria-labelledby="navbarDropdownMenuLink">
                            <li>
                                <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">{% firstof user.get_full_name user.email %}</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    {% endif %}
{% endblock navbar_links %}
{% block page_content %}
    {% block breadcrumb_nav %}
        {% if breadcrumb_trail %}
            <!-- Breadcrumbs -->
            <div class="container-fluid" id="breadcrumbs_div">
                <div class="row pt-2 bg-light">
                    <div class="col">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                {{ breadcrumb_trail|safe }}
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endblock breadcrumb_nav %}
    <div class="container-fluid">
        {% if messages %}
            <!-- Messages  -->
            <div class="row">
                <div class="col">
                    {% for message in messages %}
                        <div class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
                    {% endfor %}
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        {% endif %}
        {% block page_content_inner %}{% endblock %}
    </div>
    <!-- /.container-fluid -->
{% endblock page_content %}
{% block page_footer %}
    <footer class="footer mt-auto py-3">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-4 col-xs-12">
                    <small>Version: {{ application_version_no }}</small>
                </div>
                <div class="col-sm-8 d-none d-sm-block text-end">
                    <small>&copy; Department of Biodiversity, Conservation and Attractions</small>
                </div>
            </div>
        </div>
    </footer>
{% endblock %}
{% block base_js %}
    {{ block.super }}
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous"></script>
{% endblock %}

penguins/templates/logged_out.html
{% extends "base_penguins.html" %}
{% block breadcrumbs %}{% endblock %}
{% block page_content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <p>
                    <a href="{% url 'login' %}">Log in again</a>
                </p>
            </div>
        </div>
    </div>
{% endblock %}

penguins/templates/login.html
{% extends "base_penguins.html" %}
{% block navbar_button %}{% endblock %}
{% block navbar_links %}{% endblock %}
{% block page_content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <h4>Please log in with your email address and password:</h4>
                <form class="form-horizontal" action="" method="POST">
                    {% csrf_token %}
                    {% if form.errors %}
                        <div class="form-group">
                            <div class="col">
                                <div class="alert alert-danger">Sorry, that's not a valid email and/or password.</div>
                            </div>
                        </div>
                    {% endif %}
                    <div class="mb-3">
                        <label for="username" class="form-label">Email address</label>
                        <input type="text"
                               class="form-control"
                               name="username"
                               value=""
                               id="username">
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Password</label>
                        <input type="password"
                               class="form-control"
                               name="password"
                               value=""
                               id="password">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <input type="hidden" name="next" value="{{ next }}" />
                </form>
            </div>
        </div>
    </div>
{% endblock %}

penguins/templates/pagination.html
<nav aria-label="Page navigation">
    <ul class="pagination">
        {# 'First page' link #}
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link"
                   href="?page=1{% if query_string %}&q={{ query_string }}{% endif %}"
                   aria-label="First page">
                    <span aria-hidden="true">«</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">«</span>
            </li>
        {% endif %}
        {# 'Previous page' link #}
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link"
                   href="?page={{ page_obj.previous_page_number }}{% if query_string %}&q={{ query_string }}{% endif %}"
                   aria-label="Previous page">
                    <span aria-hidden="true">←</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">←</span>
            </li>
        {% endif %}
        {# Previous n pages #}
        {% for n in previous_pages %}
            <li class="page-item">
                <a class="page-link"
                   href="?page={{ n }}{% if query_string %}&q={{ query_string }}{% endif %}"
                   aria-label="Page {{ n }}">{{ n }}</a>
            </li>
        {% endfor %}
        {# Current page number links #}
        <li class="page-item active" aria-current="page">
            <span class="page-link">{{ page_obj.number }}</span>
        </li>
        {# Next n pages #}
        {% for n in next_pages %}
            <li class="page-item">
                <a class="page-link"
                   href="?page={{ n }}{% if query_string %}&q={{ query_string }}{% endif %}"
                   aria-label="Page {{ n }}">{{ n }}</a>
            </li>
        {% endfor %}
        {# 'Next page' link #}
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link"
                   href="?page={{ page_obj.next_page_number }}{% if query_string %}&q={{ query_string }}{% endif %}"
                   aria-label="Next page">
                    <span aria-hidden="true">→</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">→</span>
            </li>
        {% endif %}
        {# 'Last page' link #}
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link"
                   href="?page={{ page_obj.paginator.num_pages }}{% if query_string %}&q={{ query_string }}{% endif %}"
                   aria-label="Last page">
                    <span aria-hidden="true">»</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">»</span>
            </li>
        {% endif %}
    </ul>
</nav>